### ISSUE TITLE
Archive project

### ISSUE THREAD

**Issue by LorenzoSapora** [alexbowers/nova-multiple-dashboard#14]
Hey, given that nova now comes with multiple dashboards ( [v2.1.0](https://nova.laravel.com/releases/2.1.0) ) , I believe this project should be marked as archived/depreciated.

Thanks for all your hard work. I appreciate you. Look forward to your next package.

**Comment by alexbowers** [comment]
Thanks for reminding me. I'll archive now.

I actually did the work for this to be put into core, but it took a while so completely forgot I had this.
