### ISSUE TITLE
Hide dashboard on condition

### ISSUE THREAD

**Issue by Yelles** [alexbowers/nova-multiple-dashboard#3]
Hi,

Any advice for how to manage this with permission ? 
I need to display a dashboard (sidebar included) only if the user hasRole or permission to access it ?

Thanks for your work,
Regards

**Comment by alexbowers** [comment]
I haven't tested this, but I believe that the ordinary authorization for a nova dashboard would also apply here.

https://github.com/alexbowers/nova-multiple-dashboard/blob/master/src/DashboardNova.php#L45

Please can you test and confirm, if not i'll take another look at it.

**Comment by Yelles** [comment]
it works, as you expected, thanks for your help!
