### ISSUE TITLE
Dashboards visible depending on the user?

### ISSUE THREAD

**Issue by ronnytorresmtz** [alexbowers/nova-multiple-dashboard#6]
Can you explain how to make the dashboards visible depending on the logged in user?

Nice package!!!

Thanks

**Comment by alexbowers** [comment]
This works the same way any other part of nova does with the authorization.

https://github.com/alexbowers/nova-multiple-dashboard/issues/3

**Comment by ronnytorresmtz** [comment]
Do you mean with a resources policy?

Thanks for any help

**Comment by alexbowers** [comment]
Yes. The authorization code I am using it identical to the rest of nova, so policies should work fine.
